"""initial

Revision ID: 2da4848b87c7
Revises:
Create Date: 2025-06-06 06:42:29.607587

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2da4848b87c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("coin_id", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("result_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coin_id", sa.String(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("price_usd", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prices_coin_id"), "prices", ["coin_id"], unique=False)
    op.create_index(op.f("ix_prices_id"), "prices", ["id"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("coin_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price_usd", sa.Float(), nullable=False),
        sa.Column("price_clp", sa.Float(), nullable=True),
        sa.Column("price_eur", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coin_id", "date", name="uix_coin_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("price_history")
    op.drop_index(op.f("ix_prices_id"), table_name="prices")
    op.drop_index(op.f("ix_prices_coin_id"), table_name="prices")
    op.drop_table("prices")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
