"""add_s2f_deviation

Revision ID: 90478601de8b
Revises: 2da4848b87c7
Create Date: 2025-06-08 16:36:19.194177

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90478601de8b"
down_revision: Union[str, None] = "2da4848b87c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_history",
        sa.Column("s2f_deviation", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("price_history", "s2f_deviation")
    # ### end Alembic commands ###
