name: Style Checks

on: [push, pull_request]

# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"
#       - run: pip install black isort flake8
#       - run: black --check .
#       - run: isort --check .
#       - run: flake8 --max-line-length=88 --extend-ignore=E203,W503
